### PR TITLE
Make sure it works with AsyncAws forks

### PR DESCRIPTION
**Pull request by Nyholm**
Thank you very much. It was super helpful!

### CODE REVIEW

**Comment by viezel** [comment]
💪🏻

**Comment by Nyholm** [comment]
Thank you.

I'm having issues to setup DynamoDB with official SDK.. Im getting this error: 

> Aws\DynamoDb\Exception\DynamoDbException
Error executing "PutItem" on "https://dynamodb.eu-central-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://dynamodb.eu-central-1.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"com.amazon.coral.validate#ValidationException","message":"One or more parameter values were invalid: Missing (truncated...) ValidationException (client): One or more parameter values were invalid: Missing the key id in the item - {"__type":"com.amazon.coral.validate#ValidationException","message":"One or more parameter values were invalid: Missing the key id in the item"}

Do you know why?

**Comment by viezel** [comment]
Can you show what you are putting to Dynamo?

**Comment by Nyholm** [comment]
Im just hitting `/cache-add`

```
Route::get('/cache-add', function () {
    return Cache::put('AWSAsync', true);
});
```

**Comment by viezel** [comment]
Not sure if all dynamo has to be strings. Like Json encoded values. 
I’ve never used dynamo db for caching in Laravel

**Comment by viezel** [comment]
Look here https://github.com/laravel/framework/blob/master/src/Illuminate/Cache/DynamoDbStore.php#L195

Dynamo needs more info in config. How does your cache config looks like?

**Comment by Nyholm** [comment]
From the default file. 


```
        'dynamodb' => [
            'driver' => 'dynamodb',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
            'table' => env('DYNAMODB_CACHE_TABLE', 'cache'),
            'endpoint' => env('DYNAMODB_ENDPOINT'),
        ],
```

I created my table (named "cache") with partition key "id". 

Screenshot 2020-05-09 at 14 36 18

**Comment by Nyholm** [comment]
I dont find any documentation or blog posts about this featue.

**Comment by viezel** [comment]
Primary should be “key” String

**Comment by Nyholm** [comment]
Yes. Excellent

**Comment by Nyholm** [comment]
Could you give this PR a review: https://github.com/async-aws/aws/pull/572

When that is merged, I think most stuff is working =)

**Pull request merged**
